### ISSUE TITLE
PR/Merge back from SharpDiff?

### ISSUE THREAD

**Issue by xoofx** [lassevk/DiffLib#8]
Hi @lassevk 
Two years ago, I did a fork of your codeplex project to github to add support for diff3 available at [SharpDiff](https://github.com/xoofx/SharpDiff).
I thought that I contacted you at that time, but I haven't found any emails... maybe I completely forgot! Sorry for that.

I was a bit in a hurry to require diff3 lib, so I tried to follow the "[A formal investigation of diff3](http://www.cis.upenn.edu/~bcpierce/papers/diff3-short.pdf)" and quickly made a first attempt. I'm not particularly satisfied with the current implem, we are using it to perform some merge of complex graph objects and it may still have bugs (edge cases)
Anyway, if you are interested, I could make a PR, or even just discuss about it.
Let me know.

**Comment by lassevk** [comment]
I have recently (since you forked the code) rewritten most of the code to have a more consistent and pluggable API, your changes may not merge cleanly at all back into the new codebase.

Having said that, I would be interested in looking at how we could integrate something like that into this library but right now I'm not super-high priority on programming in my spare time.

If you don't mind I would like to add an item to my todo-list to pop up in November, when other spare-time things have quieted down?
